### ISSUE TITLE
Found no NVIDIA driver on your system.

### ISSUE THREAD

**Issue by dextreem** [argosopentech/argos-train#26]
While training I get the following error

```
Traceback (most recent call last):
  File "/home/argosopentech/env/bin/onmt_train", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-py', 'console_scripts', 'onmt_train')())
  File "/home/argosopentech/OpenNMT-py/onmt/bin/train.py", line 172, in main
    train(opt)
  File "/home/argosopentech/OpenNMT-py/onmt/bin/train.py", line 157, in train
    train_process(opt, device_id=0)
  File "/home/argosopentech/OpenNMT-py/onmt/train_single.py", line 64, in main
    configure_process(opt, device_id)
  File "/home/argosopentech/OpenNMT-py/onmt/train_single.py", line 19, in configure_process
    torch.cuda.set_device(device_id)
  File "/home/argosopentech/env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 326, in set_device
    torch._C._cuda_setDevice(device)
  File "/home/argosopentech/env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "/home/argosopentech/env/bin/argos-train", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/argosopentech/argos-train/bin/argos-train", line 20, in <module>
    train.train(from_code, to_code, from_name, to_name, version, package_version, argos_version, data_exists, epochs_count)
  File "/home/argosopentech/argos-train/argostrain/train.py", line 173, in train
    str(opennmt_checkpoints[-2].f),
IndexError: list index out of range
```

So, basically it cannot find my graphics card. I run it on windows in docker via

```
docker run -it argosopentech/argostrain /bin/bash
```

Do I have to enable something before starting the training?

Thanks and best regards.

**Comment by dextreem** [comment]
Running with GPUs enabled helped, now I get out of memory because of my cr*ppy GPU ;-)

```
docker run --gpus all -it argosopentech/argostrain /bin/bash
```
