### ISSUE TITLE
DigitalOcean argosdata files cannot be accessed

### ISSUE THREAD

**Issue by bruno-kakele** [argosopentech/argos-train#35]
Hi,

The following data in data-index.json cannot be fetched:

- https://argosopentech.nyc3.digitaloceanspaces.com/argospm/data-wikimatrix-en_de.argosdata
- https://argosopentech.nyc3.digitaloceanspaces.com/argospm/data-wikimatrix-en_es.argosdata
- https://argosopentech.nyc3.digitaloceanspaces.com/argospm/data-wikimatrix-en_fr.argosdata
- https://argosopentech.nyc3.digitaloceanspaces.com/argospm/data-wikimatrix-en_pt.argosdata
- https://argosopentech.nyc3.digitaloceanspaces.com/argospm/data-wikimatrix-en_ru.argosdata

I encountered this error while trying to generate a new model for ES and PT:

```
('Could not download https://argosopentech.nyc3.digitaloceanspaces.com/argospm/data-wikimatrix-en_pt.argosdata',)
Traceback (most recent call last):
  File "/home/argosopentech/env/bin/argos-train", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/argosopentech/argos-train/bin/argos-train", line 18, in <module>
    train.train(from_code, to_code, from_name, to_name, version, package_version, argos_version, data_exists)
  File "/home/argosopentech/argos-train/argostrain/train.py", line 90, in train
    source, target = dataset.data()
  File "/home/argosopentech/argos-train/argostrain/dataset.py", line 249, in data
    self.download()
  File "/home/argosopentech/argos-train/argostrain/dataset.py", line 243, in download
    f.write(data)
```

**Comment by PJ-Finlay** [comment]
Thanks for reporting this issue. The Wikimatrix data is no longer used so I removed it from the index.
