### ISSUE TITLE
Please help me solve the problem.

### ISSUE THREAD

**Issue by Sauong** [argosopentech/argos-train#36]
Please help me solve this problem.

'charmap' codec can't decode byte 0x99 in position 614: character maps to <undefined>
  File "D:\Train Model\argos-train-master\argostrain\dataset.py", line 291, in data
    self.source = self.source_file.readlines()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Train Model\argos-train-master\argostrain\data.py", line 17, in prepare_data
    source_data, target_data = dataset.data()
                               ^^^^^^^^^^^^^^
  File "D:\Train Model\argos-train-master\argostrain\train.py", line 125, in train
    argostrain.data.prepare_data(settings.SOURCE_PATH, settings.TARGET_PATH)
  File "D:\Train Model\argos-train-master\Test.py", line 18, in <module>
    train.train(from_code, to_code, from_name, to_name, version, package_version, argos_version, data_exists)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x99 in position 614: character maps to <undefined>

**Comment by Sauong** [comment]
['\n', '\n', 'Data compiled by [Opus](https://opus.nlpl.eu/).\n', '\n', 'Dictionary data from Wiktionary using [Wiktextract](https://github.com/tatuylonen/wiktextract).\n', '\n', 'Includes pretrained models from [Stanza](https://github.com/stanfordnlp/stanza/).\n', '\n', 'Credits:\n', '\n']
Traceback (most recent call last):
  File "d:\Train Model\argos-train-master\Test.py", line 18, in <module>
    train.train(from_code, to_code, from_name, to_name, version, package_version, argos_version, data_exists)
  File "d:\Train Model\argos-train-master\argostrain\train.py", line 127, in train
    argostrain.data.prepare_data(settings.SOURCE_PATH, settings.TARGET_PATH)
  File "d:\Train Model\argos-train-master\argostrain\data.py", line 17, in prepare_data
    source_data, target_data = dataset.data()
                               ^^^^^^^^^^^^^^
  File "d:\Train Model\argos-train-master\argostrain\dataset.py", line 291, in data
    self.source = self.source_file.readlines()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bird0\AppData\Local\Programs\Python\Python311\Lib\encodings\cp874.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4619: character maps to <undefined>
